name: Label Release PRs

on:
  workflow_dispatch:

jobs:
  label-release-prs:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find PRs and add label
        env:
          ORG: axonivy-market
        run: |
          repos=$(gh repo list $ORG --json name --jq '.[].name')
          for repo in $repos; do
            echo "🔍 Checking repo: $repo"
          #   prs=$(gh pr list \
          #     --repo "$ORG/$repo" \
          #     --state all \
          #     --search "Release in:title author:github-actions[bot]" \
          #     --json number,labels,state)

          #   filtered=$(echo "$prs" | jq -r '.[] | select(.state=="OPEN" or .state=="MERGED") | @base64')

          #   for pr in $filtered; do
          #     _jq() { echo $pr | base64 --decode | jq -r $1; }
          #     number=$(_jq '.number')
          #     labels=$(_jq '.labels[].name')

          #     if ! echo "$labels" | grep -q "skip-changelog"; then
          #       gh pr edit $number --repo "$ORG/$repo" --add-label "skip-changelog"
          #     fi
          #   done
          done