name: Label Release PRs

on:
  workflow_dispatch:

jobs:
  label-release-prs:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find PRs and add label
        env:
          ORG: axonivy-market
        run: |
          # List all repos in the org
          repos=$(gh repo list $ORG --limit 1000 --json name --jq '.[].name')

          for repo in $repos; do
            echo "🔎 Checking repo: $ORG/$repo"
            
            # Find all open PRs with title "Release" and author github-actions[bot]
            prs=$(gh pr list \
              --repo "$ORG/$repo" \
              --search "Release in:title author:github-actions[bot]" \
              --json number --jq '.[].number')

            for pr in $prs; do
              echo "➡️  Adding label B to $ORG/$repo PR #$pr"
            done
          done