name: Label Release PRs

on:
  workflow_dispatch:

jobs:
  label-release-prs:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find PRs and add label
        env:
          ORG: axonivy-market
        run: |
          repos=$(gh repo list $ORG --json name --jq '.[].name')
            for repo in $repos; do
              echo "🔍 Checking repo: $repo"
              prs=$(gh pr list --repo "$ORG/$repo" --search "Release in:title author:github-actions[bot]" --json number,title,author)

              if [ "$prs" != "[]" ]; then
                echo "➡️ Found PRs in $repo: $prs"
              fi
            done