name: Label Release PRs

on:
  workflow_dispatch:

jobs:
  label-release-prs:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find PRs and add label
        env:
          ORG: axonivy-market
        run: |
          repos=$(gh repo list $ORG --json name --jq '.[].name')
          for repo in $repos; do
            echo "🔍 Checking repo: $repo"
            prs=$(gh pr list \
              --repo "$ORG/$repo" \
              --state all \
              --search "Release in:title author:github-actions[bot]" \
              --json number,title,author,state,mergedAt)

            # Filter out only open or merged (skip closed)
            filtered=$(echo "$prs" | jq '[.[] | select(.state=="OPEN" or .state=="MERGED")]')

            if [ "$filtered" != "[]" ]; then
              echo "➡️ Found PRs in $repo:"
              echo "$filtered"
            fi
          done