name: Label Release PRs

on:
  workflow_dispatch:

jobs:
  label-release-prs:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find PRs and add label
        env:
          ORG: axonivy-market
        run: |
          prs=$(gh pr list --search "Release in:title author:github-actions[bot] user:axonivy-market" --json number,title,author)
          echo "Raw JSON output:"
          echo "$prs"